stages:

- stage: Build
  jobs:
  - job: Mac
    pool: 
      vmImage: macOS-latest
    steps:
    - powershell: Write-Host "##vso[task.setvariable variable=Mac.Variable;]HelloMac"
      displayName: Set Variable

  - job: Windows
    dependsOn: Mac
    pool:
      vmImage: windows-latest
    steps:
    - powershell: Write-Host '$(Mac.Variable)'
      displayName: Get Variable
