stages:

- stage: Build
  jobs:
  - job: Mac
    pool: 
      name: Hosted Mac Internal
    steps:
    - powershell: Write-Host "##vso[task.setvariable variable=MacVariable;]HelloMac"
      displayName: Set Variable

  - job: Windows
    dependsOn: Mac
    pool:
      name: Hosted Windows 2019 with VS 2019
    steps:
    - powershell: Write-Host $(MacVariable)
      displayName: Get Variable
